---

#---- Git ----#

- name: git installed
  yum:
    name: git
    state: installed
  tags: git

  - name: git name configured
  when: git
  git_config:
    name: user.name
    value: '{{ git.name }}'
    scope: global
  with_items: '{{ git }}'
  tags: git

- name: git email configured
  when: git
  git_config:
    name: user.email
    value: '{{ git.email }}'
    scope: global
  with_items: '{{ git }}'
  tags: git
